[tools]
java = "temurin-17.0.17+10.0.LTS"
just = "1.45.0"
maven = "3.9.11"
mvnd = "1.0.2"
node = "24.12.0"
"npm:markdownlint-cli" = "0.45.0"
"npm:strip-ansi-cli" = "4.0.0"

[alias]
mvnd = "asdf:https://github.com/joschi/asdf-mvnd"

[env]
TERM = 'xterm-256color'
